# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Files/AddConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddConfig(object):
    def setupUi(self, AddConfig):
        AddConfig.setObjectName("AddConfig")
        AddConfig.resize(511, 500)
        self.textBrowser_8 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_8.setGeometry(QtCore.QRect(35, 330, 241, 41))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_2.setGeometry(QtCore.QRect(35, 80, 241, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Combo_GPIOPin = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOPin.setGeometry(QtCore.QRect(285, 180, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOPin.setFont(font)
        self.Combo_GPIOPin.setEditable(True)
        self.Combo_GPIOPin.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOPin.setObjectName("Combo_GPIOPin")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPin.addItem("")
        self.Combo_GPIOPort = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOPort.setGeometry(QtCore.QRect(285, 130, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOPort.setFont(font)
        self.Combo_GPIOPort.setEditable(True)
        self.Combo_GPIOPort.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOPort.setObjectName("Combo_GPIOPort")
        self.Combo_GPIOPort.addItem("")
        self.Combo_GPIOPort.addItem("")
        self.Combo_GPIOPort.addItem("")
        self.Combo_GPIOPort.addItem("")
        self.Combo_GPIOPort.addItem("")
        self.textBrowser_4 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_4.setGeometry(QtCore.QRect(35, 130, 241, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_6.setGeometry(QtCore.QRect(35, 180, 241, 41))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.Combo_GPIOPuPd = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOPuPd.setGeometry(QtCore.QRect(285, 330, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOPuPd.setFont(font)
        self.Combo_GPIOPuPd.setEditable(True)
        self.Combo_GPIOPuPd.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOPuPd.setObjectName("Combo_GPIOPuPd")
        self.Combo_GPIOPuPd.addItem("")
        self.Combo_GPIOPuPd.addItem("")
        self.Combo_GPIOPuPd.addItem("")
        self.textBrowser_7 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_7.setGeometry(QtCore.QRect(35, 230, 241, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.GPIOName = QtWidgets.QTextEdit(AddConfig)
        self.GPIOName.setGeometry(QtCore.QRect(285, 80, 196, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.GPIOName.setFont(font)
        self.GPIOName.setObjectName("GPIOName")
        self.Combo_GPIOMode = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOMode.setGeometry(QtCore.QRect(285, 230, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOMode.setFont(font)
        self.Combo_GPIOMode.setEditable(True)
        self.Combo_GPIOMode.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOMode.setObjectName("Combo_GPIOMode")
        self.Combo_GPIOMode.addItem("")
        self.Combo_GPIOMode.addItem("")
        self.Combo_GPIOMode.addItem("")
        self.Combo_GPIOMode.addItem("")
        self.textBrowser_5 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_5.setGeometry(QtCore.QRect(35, 25, 446, 46))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_9 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_9.setGeometry(QtCore.QRect(35, 380, 241, 41))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.Combo_GPIOOType = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOOType.setGeometry(QtCore.QRect(285, 380, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOOType.setFont(font)
        self.Combo_GPIOOType.setEditable(True)
        self.Combo_GPIOOType.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOOType.setObjectName("Combo_GPIOOType")
        self.Combo_GPIOOType.addItem("")
        self.Combo_GPIOOType.addItem("")
        self.Combo_GPIOSpeed = QtWidgets.QComboBox(AddConfig)
        self.Combo_GPIOSpeed.setGeometry(QtCore.QRect(285, 280, 196, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Combo_GPIOSpeed.setFont(font)
        self.Combo_GPIOSpeed.setEditable(True)
        self.Combo_GPIOSpeed.setIconSize(QtCore.QSize(40, 40))
        self.Combo_GPIOSpeed.setObjectName("Combo_GPIOSpeed")
        self.Combo_GPIOSpeed.addItem("")
        self.Combo_GPIOSpeed.addItem("")
        self.Combo_GPIOSpeed.addItem("")
        self.Combo_GPIOSpeed.addItem("")
        self.textBrowser_10 = QtWidgets.QTextBrowser(AddConfig)
        self.textBrowser_10.setGeometry(QtCore.QRect(35, 280, 241, 41))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.Accept = QtWidgets.QPushButton(AddConfig)
        self.Accept.setGeometry(QtCore.QRect(145, 440, 131, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Accept.setFont(font)
        self.Accept.setObjectName("Accept")
        self.Cancel = QtWidgets.QPushButton(AddConfig)
        self.Cancel.setGeometry(QtCore.QRect(285, 440, 131, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(AddConfig)
        QtCore.QMetaObject.connectSlotsByName(AddConfig)

    def retranslateUi(self, AddConfig):
        _translate = QtCore.QCoreApplication.translate
        AddConfig.setWindowTitle(_translate("AddConfig", "Form"))
        self.textBrowser_8.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Pull Up/Down</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Name</span></p></body></html>"))
        self.Combo_GPIOPin.setItemText(0, _translate("AddConfig", "0"))
        self.Combo_GPIOPin.setItemText(1, _translate("AddConfig", "1"))
        self.Combo_GPIOPin.setItemText(2, _translate("AddConfig", "2"))
        self.Combo_GPIOPin.setItemText(3, _translate("AddConfig", "3"))
        self.Combo_GPIOPin.setItemText(4, _translate("AddConfig", "4"))
        self.Combo_GPIOPin.setItemText(5, _translate("AddConfig", "5"))
        self.Combo_GPIOPin.setItemText(6, _translate("AddConfig", "6"))
        self.Combo_GPIOPin.setItemText(7, _translate("AddConfig", "7"))
        self.Combo_GPIOPin.setItemText(8, _translate("AddConfig", "8"))
        self.Combo_GPIOPin.setItemText(9, _translate("AddConfig", "9"))
        self.Combo_GPIOPin.setItemText(10, _translate("AddConfig", "10"))
        self.Combo_GPIOPin.setItemText(11, _translate("AddConfig", "11"))
        self.Combo_GPIOPin.setItemText(12, _translate("AddConfig", "12"))
        self.Combo_GPIOPin.setItemText(13, _translate("AddConfig", "13"))
        self.Combo_GPIOPin.setItemText(14, _translate("AddConfig", "14"))
        self.Combo_GPIOPin.setItemText(15, _translate("AddConfig", "15"))
        self.Combo_GPIOPort.setItemText(0, _translate("AddConfig", "GPIOA"))
        self.Combo_GPIOPort.setItemText(1, _translate("AddConfig", "GPIOB"))
        self.Combo_GPIOPort.setItemText(2, _translate("AddConfig", "GPIOC"))
        self.Combo_GPIOPort.setItemText(3, _translate("AddConfig", "GPIOD"))
        self.Combo_GPIOPort.setItemText(4, _translate("AddConfig", "GPIOE"))
        self.textBrowser_4.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Port</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Pin</span></p></body></html>"))
        self.Combo_GPIOPuPd.setItemText(0, _translate("AddConfig", "NO Pull"))
        self.Combo_GPIOPuPd.setItemText(1, _translate("AddConfig", "Pull Up"))
        self.Combo_GPIOPuPd.setItemText(2, _translate("AddConfig", "Pull Down"))
        self.textBrowser_7.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Mode</span></p></body></html>"))
        self.GPIOName.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.Combo_GPIOMode.setItemText(0, _translate("AddConfig", "Input Mode"))
        self.Combo_GPIOMode.setItemText(1, _translate("AddConfig", "Output Mode"))
        self.Combo_GPIOMode.setItemText(2, _translate("AddConfig", "Alternate Function"))
        self.Combo_GPIOMode.setItemText(3, _translate("AddConfig", "Analog Mode"))
        self.textBrowser_5.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#00aa00;\">Adding GPIO Configuration</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Output Type</span></p></body></html>"))
        self.Combo_GPIOOType.setItemText(0, _translate("AddConfig", "Push-Pull"))
        self.Combo_GPIOOType.setItemText(1, _translate("AddConfig", "Open-Drain"))
        self.Combo_GPIOSpeed.setItemText(0, _translate("AddConfig", "Low Speed"))
        self.Combo_GPIOSpeed.setItemText(1, _translate("AddConfig", "Medium Speed"))
        self.Combo_GPIOSpeed.setItemText(2, _translate("AddConfig", "High Speed"))
        self.Combo_GPIOSpeed.setItemText(3, _translate("AddConfig", "Very High Speed"))
        self.textBrowser_10.setHtml(_translate("AddConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">GPIO Speed</span></p></body></html>"))
        self.Accept.setText(_translate("AddConfig", "OK"))
        self.Cancel.setText(_translate("AddConfig", "Cancel"))
